round-holder:
  initial-round-goal: 500
  max-cacheable-round-goal: 9000000

management:
  endpoints:
    web:
      exposure:
        include: metrics, prometheus
  metrics:
    enable:
      tomcat: true
      jvm: false
      process: false
      system: false
      logback: false

